[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
i11n_escrow = "BDQUZodt8GCPALEFAQALY83v2w2ikVu7YJNSMYzV91YK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
